# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgba(c1505cee) rgba(5c7fb8ee) 45deg
$inactiveBorderColor = rgba(4a454eaa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 2
    gaps_out = 2
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 0
    rounding_power = 0
}
